# Site settings
title: Wai's Way
email: info@waisway.com
url: https://gwaydust.github.io/waiswaywebsite/
description: "Solutions in Mobile and Web development, Devops Automation and RPA."
keywords: "Mobile development, web development, Devops, Test Automation, RPA"
skills: "Mobile and Web development. Devops Automation and RPA"
meta_author: Wai's Way

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Wai's Way Tech
  location: Locations
  social: Around the Web
  credits: Technology

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: https://stackoverflow.com/users/524607/gway
  - title: github
    url: http://github.com/gwaydust

# Postal address (add as many lines as necessary)
address:
  - line: <b>Hong Kong Office</b> <a href="https://goo.gl/maps/qsnY2S2AxDEp2sWk6"><i class="fa fa-map-marker"></i></a>
  - line: "714 Prince Edward Rd E, Rm. 32, 17/F, Chaip King Industrial Building"
  - line: San Po Kong, Kowloon, Hong Kong 
  - line:
  - line: <b>US Office</b> <a href="https://goo.gl/maps/woQaTfrZMXzEP6gHA"><i class="fa fa-map-marker"></i></a>
  - line: 11923 NE Sumner St, STE 887567
  - line: Portland, Oregon, 97250, USA 
  - line:
  - line: <i class="fa fa-phone"></i> 1-916-620-7205 
  - line: <i class="fa fa-phone"></i> +852-9823-9016 
  - line: <i class="fa fa-envelope"></i> <a href="mailto:info@waisway.com">info@waisway.com</a>


# Credits content
credits: 'This Website is powered by <a href="http://startbootstrap.com">Bootstrap</a> and <a href="https://jekyllrb.com/">Jekyll</a>.'

# Build settings
markdown: kramdown
permalink: pretty
